/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alex
 */
public class AsignaciondeCursoAlumno extends javax.swing.JFrame {

    /**
     * Creates new form AsignaciondeCursoAlumno
     */
    public AsignaciondeCursoAlumno() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarCursosAsignados();
    }

    private void mostrarCursosAsignados() {
        Alumno alumnoLogeado = Loginb.alumnoLogeado;

        if (alumnoLogeado != null) {
            DefaultTableModel data = new DefaultTableModel(new String[]{"Nombre", "Sección", "Profesor", "Nota"}, 0);

            for (Curso c : Loginb.cursos) {
                for (Alumno a : c.getAlumnos()) {
                    if (a.nombre.equals(alumnoLogeado.nombre)) {
                        data.addRow(new Object[]{c.getnombreCurso(), c.getSeccionCurso(), c.getProfesorSeleccionado(), a.getNota()});
                        break;
                    }
                }
            }
            jTable1.setModel(data);
        } else {
            System.out.println("No se encontro el alumno");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Desasignar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(43, 43, 43)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AsignardesdeAlumnos n = new AsignardesdeAlumnos();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Alumno alumnoLogeado = Loginb.alumnoLogeado;

        if (alumnoLogeado != null) {
            int cursoAsignadoIndex = jTable1.getSelectedRow();
            if (cursoAsignadoIndex == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, selecciona un curso para desasignarte", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String nombreCurso = jTable1.getValueAt(cursoAsignadoIndex, 0).toString();

                Curso cursoSeleccionado = null;
                for (Curso c : Loginb.cursos) {
                    if (c.getnombreCurso().equals(nombreCurso)) {
                        cursoSeleccionado = c;
                        break;
                    }
                }
                if (cursoSeleccionado != null) {
                    boolean alumnoEncontrado = false;
                    for (Alumno a : cursoSeleccionado.getAlumnos()) {
                        if (a.carne.equals(alumnoLogeado.carne)) {
                            cursoSeleccionado.getAlumnos().remove(a);
                            alumnoEncontrado = true;
                            break;
                        }
                    }
                    if (alumnoEncontrado) {
                        JOptionPane.showMessageDialog(this, "Te desasignaste exitosamente");
                        mostrarCursosAsignados();
                    } else {
                        JOptionPane.showMessageDialog(this, "El alumno no está asignado a este curso", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       BienvenidaAlumno c = new BienvenidaAlumno();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
