/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb;

import javax.swing.JOptionPane;

/**
 *
 * @author alex
 */
public class AsignardesdeAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form AsignardesdeAlumnos
     */
    public AsignardesdeAlumnos() {
        initComponents();
        jLabel1.setText("Bienvenido Alumno: " + Loginb.alumnoLogeado.getNombre() + " " + Loginb.alumnoLogeado.getApellido() + " " + Loginb.alumnoLogeado.getCarne());

        for (Curso e : Loginb.cursos) {
            jComboBox1.addItem(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel2.setText("Curso: ");

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addComponent(jButton2)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombreCurso = jComboBox1.getSelectedItem().toString();

        if (nombreCurso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un curso", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Alumno alumnoLogeado = Loginb.alumnoLogeado;

        if (alumnoLogeado == null) {
            JOptionPane.showMessageDialog(this, "No hay ningún alumno logeado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Curso cursoSeleccionado = null;
        for (Curso curso : Loginb.cursos) {
            if (curso.toString().equals(nombreCurso)) {
                cursoSeleccionado = curso;
                break;
            }
        }

        if (cursoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "El curso seleccionado no existe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (Alumno alumno : cursoSeleccionado.getAlumnos()) {
            if (alumno.getCarne().equals(alumnoLogeado.getCarne())) {
                JOptionPane.showMessageDialog(this, "El alumno ya está asignado a este curso.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        int contarCursos = 0;
        for (Curso curso : Loginb.cursos) {
            for (Alumno alumno : curso.getAlumnos()) {
                if (alumno.getCarne().equals(alumnoLogeado.getCarne())) {
                    contarCursos++;
                }
            }
        }

        if (contarCursos >= 5) {
            JOptionPane.showMessageDialog(this, "El alumno ya está asignado a 5 cursos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Alumno nuevoAlumno = new Alumno();
        nuevoAlumno.setNombre(alumnoLogeado.getNombre());
        nuevoAlumno.setApellido(alumnoLogeado.getApellido());
        nuevoAlumno.setCarne(alumnoLogeado.getCarne());
        nuevoAlumno.setPassword(alumnoLogeado.getPassword());
        nuevoAlumno.setNota(alumnoLogeado.getNota());

        cursoSeleccionado.getAlumnos().add(nuevoAlumno);

        JOptionPane.showMessageDialog(this, "La asignación de cursos fue exitosa");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AsignaciondeCursoAlumno n = new AsignaciondeCursoAlumno();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
