/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import org.w3c.dom.Document;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author alex
 */
public class ConsultarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarAlumno
     */
    public ConsultarAlumno() {
        initComponents();

        this.setLocationRelativeTo(null);

        DefaultTableModel data = new DefaultTableModel(new String[]{"Carne", "Nombre", "Apellido", "Password"}, Loginb.alumnos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Alumno p : Loginb.alumnos) {
            jTable1.setValueAt(p.carne, row, 0);
            jTable1.setValueAt(p.nombre, row, 1);
            jTable1.setValueAt(p.apellido, row, 2);
            jTable1.setValueAt(p.password, row, 3);
            row++;
        }
    }

    public void actualizarDatos() {
        DefaultTableModel data = new DefaultTableModel(new String[]{"Carne", "Nombre", "Apellido", "Password"}, Loginb.alumnos.size());
        jTable1.setModel(data);

        int row = 0;

        for (Alumno p : Loginb.alumnos) {
            jTable1.setValueAt(p.carne, row, 0);
            jTable1.setValueAt(p.nombre, row, 1);
            jTable1.setValueAt(p.apellido, row, 2);
            jTable1.setValueAt(p.password, row, 3);
            row++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cargar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Administrador c = new Administrador();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ModificarAlumno s = new ModificarAlumno(jTable1.getSelectedRow());
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        StringBuilder contenido = new StringBuilder("<alumnos>\n");

        for (Alumno alu : Loginb.alumnos) {
            contenido.append("\t<alumno>\n")
                    .append("\t\t<carne>").append(alu.getCarne()).append("</carne>\n")
                    .append("\t\t<nombre>").append(alu.getNombre()).append("</nombre>\n")
                    .append("\t\t<apellido>").append(alu.getApellido()).append("</apellido>\n")
                    .append("\t\t<password>").append(alu.getPassword()).append("</password>\n")
                    .append("\t</alumno>\n");
        }
        contenido.append("</alumnos>");

        JFileChooser archivo = new JFileChooser();
        int seleccionado = archivo.showSaveDialog(this);
        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            guardarXML(archivo.getSelectedFile().toPath().toString(), contenido.toString());
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser("");
        int seleccionado = archivo.showDialog(this, "Cargar");
        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            leerXML(archivo.getSelectedFile());

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void leerXML(File archivo) {
        try {
            DocumentBuilderFactory xml = DocumentBuilderFactory.newInstance();
            DocumentBuilder xm = xml.newDocumentBuilder();
            Document x = xm.parse(archivo);

            x.getDocumentElement().normalize();
            NodeList nodos = x.getElementsByTagName("alumno");
            for (int i = 0; i < nodos.getLength(); i++) {
                Node n = nodos.item(i);
                if (n.getNodeType() == Node.ELEMENT_NODE) {
                    Element e = (Element) n;
                    Alumno al = new Alumno();
                    al.carne = e.getElementsByTagName("carne")
                            .item(0).getTextContent();
                    al.nombre = e.getElementsByTagName("nombre")
                            .item(0).getTextContent();
                    al.apellido = e.getElementsByTagName("apellido")
                            .item(0).getTextContent();
                    al.password = e.getElementsByTagName("password")
                            .item(0).getTextContent();
                    Loginb.alumnos.add(al);
                }
            }
            actualizarDatos();
        } catch (Exception e) {

        }
    }

    public void guardarXML(String rutaConNombre, String contenido) {
        try (FileWriter fw = new FileWriter(rutaConNombre); PrintWriter pw = new PrintWriter(fw)) {
            pw.write(contenido);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo XML.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
