/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.loginb;

import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author alex
 */
public class ConsultarCurso extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCurso
     */
    public ConsultarCurso() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarCursosEnTabla();

    }

    private void mostrarCursosEnTabla() {

        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID", "Nombre", "Sección", "Fecha inicio", "Fecha fin", "Hora inicio", "Hora fin", "Profesor"}, 0);

        for (Curso curso : Loginb.cursos) {
            model.addRow(new Object[]{
                curso.getidCurso(),
                curso.getnombreCurso(),
                curso.getSeccionCurso(),
                curso.getFechaInicioCurso(),
                curso.getFechaFinCurso(),
                curso.getHoraInicioCurso(),
                curso.getHoraFinCurso(),
                curso.getProfesorSeleccionado()
            });
        }

        jTable1.setModel(model);
    }

    public void actualizarDatos() {
        DefaultTableModel model = new DefaultTableModel(new Object[]{"ID", "Nombre", "Sección", "Fecha inicio", "Fecha fin", "Hora inicio", "Hora fin", "Profesor"}, 0);
        jTable1.setModel(model);

        for (Curso curso : Loginb.cursos) {
            model.addRow(new Object[]{
                curso.getidCurso(),
                curso.getnombreCurso(),
                curso.getSeccionCurso(),
                curso.getFechaInicioCurso(),
                curso.getFechaFinCurso(),
                curso.getHoraInicioCurso(),
                curso.getHoraFinCurso(),
                curso.getProfesorSeleccionado()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 180));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jButton3.setText("Cargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Administrador c = new Administrador();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ModificarCurso o = new ModificarCurso(jTable1.getSelectedRow());
        o.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser("");
        int seleccionado = archivo.showDialog(null, "Cargar");
        if (seleccionado == JFileChooser.APPROVE_OPTION) {
            leerJSON(archivo.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void leerJSON(String rutaConNombre) {
        JSONParser parser = new JSONParser();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");

        try (FileReader reader = new FileReader(rutaConNombre)) {
            Object obj = parser.parse(reader);
            JSONArray cursosList = (JSONArray) obj;

            for (Object c : cursosList) {
                JSONObject cursoObj = (JSONObject) c;

                if (cursoObj != null) {
                    Object idObject = cursoObj.get("id");
                    int idCurso = (idObject != null) ? ((Long) idObject).intValue() : 1;
                    String nombreCurso = (String) cursoObj.get("nombre");
                    String seccionCurso = (String) cursoObj.get("seccion");

                    String fechaInicioTexto = (String) cursoObj.get("fecha_inicio");
                    Date fechaInicioCurso = (fechaInicioTexto != null && !fechaInicioTexto.isEmpty())
                            ? dateFormat.parse(fechaInicioTexto) : null;

                    String fechaFinTexto = (String) cursoObj.get("fecha_fin");
                    Date fechaFinCurso = (fechaFinTexto != null && !fechaFinTexto.isEmpty())
                            ? dateFormat.parse(fechaFinTexto) : null;

                    String horaInicioCurso = (String) cursoObj.get("hora_inicio");
                    String horaFinCurso = (String) cursoObj.get("hora_fin");
                    String profesorSeleccionado = (String) cursoObj.get("profesor");

                    Curso curso = new Curso(idCurso, nombreCurso, seccionCurso, fechaInicioCurso, fechaFinCurso,
                            horaInicioCurso, horaFinCurso, profesorSeleccionado);

                    Loginb.cursos.add(curso);
                }
            }

            actualizarDatos();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
